# Generated by Django 3.2.8 on 2021-11-06 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_todo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('done_for', models.TextField()),
                ('today', models.TextField()),
                ('important', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
    ]
