# Generated by Django 3.2.8 on 2021-11-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_habits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='done_for',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='habits',
            name='today',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
