# Generated by Django 3.2.8 on 2021-11-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211106_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='done_for',
            field=models.TextField(),
        ),
    ]
