# Generated by Django 3.2.8 on 2021-11-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_habits_done_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='today',
            field=models.DateField(auto_now_add=True),
        ),
    ]
