# Generated by Django 3.2.8 on 2021-11-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_habits_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='done_for',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='habits',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
